version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: hearth
      POSTGRES_USER: hearth_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://hearth_user:supersecretpassword@db:5432/hearth?sslmode=disable
    ports:
      - "8080:8080"
    # Uncomment if you want live reload in development:
    # volumes:
    #   - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    # Uncomment for hot reload in development:
    # volumes:
    #   - ./frontend:/app

volumes:
  pgdata:
